#!/bin/bash

input=($(cat input))

# init this array to ${#input[1]}
arr=(0 0 0 0 0 0 0 0 0 0 0 0)

# find most common second bit of number
# aka gamma rate
for (( i=0;i<${#input[@]};i++ )); do
	tmp=${input[i]}
	for (( j=0;j<${#tmp};j++ )); do
		case ${tmp:j:1} in
			0)
				arr[j]=`expr ${arr[j]} - 1`
				;;
			1)
				arr[j]=`expr ${arr[j]} + 1`
				;;
		esac done
done

xarr=()
for (( i=0;i<${#arr[@]};i++ )); do
	if [ ${arr[i]} -gt 0 ]; then
		arr[i]=1
		xarr[i]=0
	else 
		arr[i]=0
		xarr[i]=1
	fi
done

# for fast test
#arr=(1 0 0 1 1 1 0 0 0 1 1 0)
#xarr=(0 1 1 0 0 0 1 1 1 0 0 1)

# binary number array to number
function A2N()
{
	tmp=("$@")
	result=0
	for (( i=0;i<${#tmp[@]};i++ )); do
		# TODO to one line?
		foo=$((10**$((${#tmp[@]}-${i}-1))))
		bar=$((${foo}*${tmp[i]}))
		result=$((${result}+${bar}))
	done
	echo $result
}

decarr=$(A2N "${arr[@]}")
decxarr=$(A2N "${xarr[@]}")
echo $(( $((2#${decarr})) * $((2#${decxarr})) ))
