#!/bin/bash

input=($(cat input))

# 1010111000111
# 1101011010101

# oxygen generator rating array
oxgenarr=()
# co2 scrubber rating array
co2scarr=()

pos=0 # for loop count position
while(( ${#oxgenarr[@]}!=1 )); do
	count=0
	# it's position bit is one
	bitone=()
	# it's position bit is zero
	bitzero=()

	for (( i=0;i<${#input[@]};i++ )); do
		tmp=${input[i]}
		case ${tmp:pos:1} in
			0)
				count=`expr ${count} - 1`
				bitzero+=(${tmp})
				;;
			1)
				count=`expr ${count} + 1`
				bitone+=(${tmp})
				;;
		esac
	done

	if [ ${count} -gt 0 ]; then
		oxgenarr=(${bitone[@]})
	else
		oxgenarr=(${bitzero[@]})
	fi

	if [ ${pos} -eq ${#input[1]} ]; then
		break
	fi

	pos=`expr ${pos} + 1`
done

